# Generated by UtilMeta 2.6.0 on 2024-11-13 05:54
# generator spec: openapi 3.1.0
# generator class: utilmeta.core.cli.specs.openapi.OpenAPIClientGenerator
from utilmeta.core import api, cli, response, request
import utype


class schemas:
    class UserSchema(utype.Schema):
        __options__ = utype.Options(addition=True)
        username: str = utype.Field(required=False, max_length=20)
        articles_num: int = utype.Field(ge=0, required=False)

    class ArticleSchema(utype.Schema):
        __options__ = utype.Options(addition=True)
        id: int = utype.Field(required=False, ge=1, le=2147483647)
        author: "schemas.UserSchema" = utype.Field(required=False)
        content: str = utype.Field(required=False)


class responses:
    class article_get_response(response.Response):
        content_type = "application/json"
        result: schemas.ArticleSchema


class APIClient(cli.Client):
    @api.get("/article", tags=["article"], description="")
    def article_get(
        self, id: int = request.QueryParam(required=True)
    ) -> responses.article_get_response[200]: pass


client = APIClient(base_url="http://127.0.0.1:8002")
