# Generated by Django 4.2.1 on 2024-04-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0003_aggregationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstoken",
            name="subject",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="token_id",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="alerttype",
            name="ident",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="alerttype",
            name="target",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="resource",
            name="remote_id",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="route",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="init_key",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="resources_etag",
            field=models.TextField(default=None, null=True),
        ),
    ]
