# Generated by Django 4.2.17 on 2026-02-11 04:32

from django.db import migrations, models
import django.db.models.deletion
import utype.utils.encode


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0005_remove_resource_deleted_querylog_model_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alertlog",
            old_name="data",
            new_name="details",
        ),
        migrations.RenameField(
            model_name="alertlog",
            old_name="relieved_time",
            new_name="recovered_time",
        ),
        migrations.RenameField(
            model_name="supervisor",
            old_name="operation_timeout",
            new_name="default_timeout",
        ),
        migrations.RenameField(
            model_name="supervisor",
            old_name="aggregate_settings",
            new_name="report_settings",
        ),
        migrations.RemoveField(
            model_name="alertlog",
            name="trigger_times",
        ),
        migrations.RemoveField(
            model_name="alertlog",
            name="trigger_values",
        ),
        migrations.RemoveField(
            model_name="alertlog",
            name="type",
        ),
        migrations.RemoveField(
            model_name="requestlog",
            name="dns_error",
        ),
        migrations.RemoveField(
            model_name="requestlog",
            name="ssl_error",
        ),
        migrations.RemoveField(
            model_name="supervisor",
            name="task_settings",
        ),
        migrations.AddField(
            model_name="aggregationlog",
            name="utcoffset",
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="alertlog",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="alertlog",
            name="event_id",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="alertlog",
            name="impact",
            field=models.JSONField(
                default=None, encoder=utype.utils.encode.JSONEncoder, null=True
            ),
        ),
        migrations.AddField(
            model_name="alertlog",
            name="latest_alarm_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="alertlog",
            name="message",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="alertlog",
            name="node_id",
            field=models.CharField(
                db_index=True, default=None, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="alertlog",
            name="remote_id",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="alertlog",
            name="remote_recovered_time",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="alertlog",
            name="service",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alertlog",
            name="settings_data",
            field=models.JSONField(
                default=None, encoder=utype.utils.encode.JSONEncoder, null=True
            ),
        ),
        migrations.AddField(
            model_name="alertlog",
            name="settings_id",
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="alertlog",
            name="settings_name",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="alertlog",
            name="severity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alertlog",
            name="supervisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_logs",
                to="ops.supervisor",
            ),
        ),
        migrations.AddField(
            model_name="alertlog",
            name="target",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_logs",
                to="ops.resource",
            ),
        ),
        migrations.AddField(
            model_name="alertlog",
            name="triggered_values",
            field=models.JSONField(
                default=dict, encoder=utype.utils.encode.JSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="databasemonitor",
            name="idle_connections_percent",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="databasemonitor",
            name="server_connections_percent",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="instancemonitor",
            name="used_space",
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="querylog",
            name="details",
            field=models.JSONField(
                default=None, encoder=utype.utils.encode.JSONEncoder, null=True
            ),
        ),
        migrations.AddField(
            model_name="requestlog",
            name="details",
            field=models.JSONField(
                default=None, encoder=utype.utils.encode.JSONEncoder, null=True
            ),
        ),
        migrations.AddField(
            model_name="requestlog",
            name="instance",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instance_request_logs",
                to="ops.resource",
            ),
        ),
        migrations.AddField(
            model_name="servermonitor",
            name="used_space",
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="servicelog",
            name="details",
            field=models.JSONField(
                default=None, encoder=utype.utils.encode.JSONEncoder, null=True
            ),
        ),
        migrations.AddField(
            model_name="supervisor",
            name="last_heartbeat",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="used_space",
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="workermonitor",
            name="used_space",
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="servicelog",
            name="endpoint_ident",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="servicelog",
            name="endpoint_ref",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="servicelog",
            name="user_id",
            field=models.TextField(db_index=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name="AlertType",
        ),
    ]
